### PR TITLE
homepage-loading: make it clear that the homepage is loading, via text, ...

### PR DESCRIPTION
**Pull request by talos**
...spinner, and cursor

### CODE REVIEW

**Comment by antoviaque** [comment]
If you can have a look at this one too? There is a small conflict with master, which I fixed while attempting to merge, but this also seem to make the loading indicator test fail:

```
antoviaque@antoviaque-laptop ~/prog/languagelearning (master) 
$ make test-client
node_modules/.bin/mocha-phantomjs -R dot http://localhost:8000/ --view 800x600 

  ․․․․․․․․․․․․․․
Error: expected false to equal true

  http://localhost:8000/static/test/vendor/expect.js:99
  http://localhost:8000/static/test/vendor/expect.js:203
  http://localhost:8000/static/test/vendor/expect.js:73
  http://localhost:8000/static/test/index.test.js:199
  http://localho․․․․․․․/static/js/vendor/tracekit.js:977


  ✖ 1 of 21 tests failed:

  1) The loaded index page after submitting an expression for translation if the expression is in a language besides English should display a loading indicator:
     Error: expected false to equal true (http://localhost:8000/static/test/vendor/expect.js:99)



make: *** [test-client] Error 1
```

**Comment by talos** [comment]
Having a look.

**Comment by talos** [comment]
This one is proving a bit tenacious -- I think I need to take a little time off then look again.  Is it a blocker for you at all?

**Comment by antoviaque** [comment]
@talos Not at all, take the time you need. : )

**Comment by talos** [comment]
@antoviaque As you can see above, I also merged in 'error-message-on-failure' into here -- to get a better sense of the scope of changes in this pull request, you should merge that branch into `master` first. I did this to make sure we don't run into additional cascading code conflicts.

**Comment by antoviaque** [comment]
Looking good - merged!

**Pull request merged**
