### PR TITLE
consistent-back-forward: terminate rendering of unneeded requests, keep ...

### PR DESCRIPTION
**Pull request by talos**
...a small cache of already made requests, fix bug that could cause back/forward + loading to clear screen

### CODE REVIEW

**Comment by antoviaque** [comment]
Looks good, but it's missing tests for the fixes & the caching mechanism. :p Merging this pull request, but putting it in the ticket to remember to add.

**Comment by talos** [comment]
Argh, my bad -- I believe tests are there for all other pull requests, thanks for calling this one out.  Since there were other test changes in the other pulls, I'll tackle this once those are merged.

**Comment by antoviaque** [comment]
Sounds good - I'm going through the other ones right now, hopefully it won't be too long. : )

**Comment by talos** [comment]
@antoviaque New pull request opened: https://github.com/antoviaque/languagelearning/pull/24

**Pull request merged**
