### PR TITLE
progress-cursor: show progress cursor when loading info

### PR DESCRIPTION
**Pull request by talos**

### CODE REVIEW

**Comment by antoviaque** [comment]
The patch looks good - could you have a look at the conflicts with master though? The tests have been shuffled somewhat. Good for me to merge directly with master.

**Comment by talos** [comment]
Looking now -- I'll do a merge against master and push back to this pull request.

**Comment by talos** [comment]
@antoviaque Did a merge, should resolve those issues -- there were some real code issues coming up (involving how the count is done to determine which cursor to display).

**Comment by antoviaque** [comment]
Looks good, thanks! Merging to master.

**Pull request merged**
